-- Portfolio QLIO : tables et droits
create table if not exists public.learning_criticals (
  id bigint generated by default as identity primary key,
  category text not null check (category in ('Organisation','Logistique','Qualité')),
  sort_order integer not null,
  title text not null,
  context text not null default '',
  objective text not null default '',
  actions text not null default '',
  evidence text not null default '',
  result text not null default '',
  reflection text not null default ''
);

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade
);

alter table public.learning_criticals enable row level security;
alter table public.admin_users enable row level security;

grant select on public.learning_criticals to anon, authenticated;
grant update on public.learning_criticals to authenticated;
grant select on public.admin_users to authenticated;

drop policy if exists "Portfolio public read" on public.learning_criticals;
create policy "Portfolio public read" on public.learning_criticals
  for select to anon, authenticated using (true);

drop policy if exists "Admins update portfolio" on public.learning_criticals;
create policy "Admins update portfolio" on public.learning_criticals
  for update to authenticated
  using (exists (select 1 from public.admin_users a where a.user_id = (select auth.uid())))
  with check (exists (select 1 from public.admin_users a where a.user_id = (select auth.uid())));

drop policy if exists "Admins can check own admin row" on public.admin_users;
create policy "Admins can check own admin row" on public.admin_users
  for select to authenticated using (user_id = (select auth.uid()));

-- 28 fiches de départ à personnaliser : 9 Organisation, 10 Logistique, 9 Qualité.
insert into public.learning_criticals (category, sort_order, title)
select 'Organisation', n, 'Apprentissage critique Organisation ' || n
from generate_series(1,9) n
where not exists (select 1 from public.learning_criticals where category='Organisation');

insert into public.learning_criticals (category, sort_order, title)
select 'Logistique', n, 'Apprentissage critique Logistique ' || n
from generate_series(1,10) n
where not exists (select 1 from public.learning_criticals where category='Logistique');

insert into public.learning_criticals (category, sort_order, title)
select 'Qualité', n, 'Apprentissage critique Qualité ' || n
from generate_series(1,9) n
where not exists (select 1 from public.learning_criticals where category='Qualité');
